export { default as Footer } from "./footer";
export { default as NavBar } from "./navbar";
export { default as Header } from "./header";
export { default as SectionPalettes } from "./section-palettes";
export { default as SectionInputColor } from "./section-input-color";
export { default as SectionSavePalette } from "./section-save-palette";
export { default as ArticlePaletteAboutTones } from "./article-palette-about-tones";
export { default as ArticlePaletteAboutSave } from "./article-palette-about-save";
export { default as ArticlePaletteAboutCreate } from "./article-palette-about-create";
